# Generated by Django 5.0.14 on 2026-03-03 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='가족/그룹명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(related_name='family_groups', to=settings.AUTH_USER_MODEL, verbose_name='소속 멤버')),
            ],
            options={
                'verbose_name': '가족 그룹',
                'verbose_name_plural': '가족 그룹 목록',
            },
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_type', models.CharField(choices=[('100Y', '100년 일기 (개인)'), ('COLLAB', '함께 쓰는 일기 (특정 사용자 공유)'), ('FAMILY', '가족 일기 (가족 그룹 공유)')], default='100Y', max_length=10, verbose_name='일기 유형')),
                ('target_date', models.DateField(help_text='실제 일기에 해당하는 날짜 (100년 일기 기준점)', verbose_name='일기 대상 날짜')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='본문 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_diaries', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('shared_users', models.ManyToManyField(blank=True, help_text='함께 쓰는 일기 선택 시 지정', related_name='shared_diaries', to=settings.AUTH_USER_MODEL, verbose_name='공유 대상 사용자')),
                ('family_group', models.ForeignKey(blank=True, help_text='가족 일기 선택 시 지정', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_diaries', to='diary.familygroup', verbose_name='지정 가족 그룹')),
            ],
            options={
                'verbose_name': '일기',
                'verbose_name_plural': '일기 목록',
                'ordering': ['-target_date', '-created_at'],
                'indexes': [models.Index(fields=['target_date'], name='diary_diary_target__703549_idx'), models.Index(fields=['diary_type'], name='diary_diary_diary_t_6bb660_idx'), models.Index(fields=['author'], name='diary_diary_author__cd7975_idx')],
            },
        ),
    ]
