"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=hdhzp#*et_hpdv&l6s4*e^@#@wf*qmm)#0_as=$@_zexr*q6k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# 1. 접속 허용 도메인 (ALLOWED_HOSTS)
# 보안을 위해 모든 도메인('*')보다는 실제 사용하는 도메인을 명시하는 것이 좋습니다.
ALLOWED_HOSTS = [
    'cosri.synology.me',
    'localhost',
    '127.0.0.1',
    '*' # 개발 중 편의를 위해 넣어둠 (나중에 배포 시 제거)
]

# 2. CSRF 신뢰 도메인 (CSRF_TRUSTED_ORIGINS) - ★ 중요 ★
# HTTPS 접속 시 로그인이 안 되거나 폼 전송 에러(CSRF Error)를 막기 위해 필수입니다.
# 반드시 'https://'를 포함해야 합니다.
##CSRF_TRUSTED_ORIGINS = [
##    'https://django.cosri.synology.me',
##    'https://code.cosri.synology.me',
##]
CSRF_TRUSTED_ORIGINS = [
    # 장고 웹 서비스 접속 주소 (필수)
    'https://cosri.synology.me:7443',

    # (선택) 만약 Code-Server 내부에서 장고로 API 요청을 보내거나,
    # Code-Server의 미리보기 기능으로 장고를 띄울 때 에러가 난다면 추가
    'https://cosri.synology.me:9443',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # [추가] 정적 파일 서빙용
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dg',           # 방금 생성한 DB 이름
        'USER': 'dg',           # 방금 생성한 DB 사용자
        'PASSWORD': 'qqaa12az~!DG',      # 사용자 비밀번호
        'HOST': '127.0.0.1',             # 호스트 네트워크 공유
        'PORT': '3307',                  # 시놀로지 MariaDB 10 포트 (중요)
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'  # [추가] 배포 시 정적 파일이 모이는 폴더

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
