# Generated by Django 5.0.14 on 2026-03-07 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='계정코드')),
                ('name', models.CharField(max_length=50, verbose_name='계정과목명')),
                ('account_type', models.CharField(choices=[('ASSET', '자산'), ('LIABILITY', '부채'), ('EQUITY', '자본'), ('REVENUE', '수익'), ('EXPENSE', '비용')], max_length=15, verbose_name='분류')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
            ],
            options={
                'verbose_name': '계정과목',
                'verbose_name_plural': '계정과목 목록',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='거래처명')),
                ('business_number', models.CharField(blank=True, max_length=20, verbose_name='사업자등록번호')),
                ('contact_info', models.CharField(blank=True, max_length=200, verbose_name='연락처/이메일')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '거래처',
                'verbose_name_plural': '거래처 목록',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='거래 일자')),
                ('title', models.CharField(max_length=200, verbose_name='거래 요약(적요)')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='accounting/evidence/%Y/%m/', verbose_name='증빙 파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='입력 일시')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '전표',
                'verbose_name_plural': '전표 목록',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='상세 적요')),
                ('debit', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='차변(입금/자산증가 등)')),
                ('credit', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='대변(출금/부채증가 등)')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='계정과목')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.journalentry', verbose_name='소속 전표')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.partner', verbose_name='거래처')),
            ],
            options={
                'verbose_name': '분개 상세',
                'verbose_name_plural': '분개 상세 목록',
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date'], name='accounting__date_e3f521_idx'),
        ),
    ]
